l <- read.csv('~/Dropbox/GenreProject/python/reception/poetry/linearpredictions.csv')
l$birthdate[l$birthdate < 1750] <- NA
model = glm(data = l, formula = as.integer(reviewed == 'rev') ~ logistic + birthdate, family = binomial(logit))
intercept = coef(model)[1] / (-coef(model)[2])
slope = coef(model)[3] / (-coef(model)[2])
line = intercept + (slope * l$birthdate)
true = sum(l$logistic > line & l$reviewed == 'rev', na.rm = TRUE) + sum(l$logistic <= line & l$reviewed == 'not', na.rm = TRUE)
false = sum(l$logistic < line & l$reviewed == 'rev', na.rm = TRUE) + sum(l$logistic >= line & l$reviewed == 'not', na.rm = TRUE)
print(true / (true + false))
levels(l$actually) = c('norton', 'norton', 'random', 'reviewed')
p <- ggplot(l, aes(x = pubdate, y = logistic, color = actually, shape = actually, size = actually)) + geom_point() + geom_smooth(method = lm, se = TRUE, size = 2) + scale_color_manual(values = c('mediumorchid1', 'gray65', 'dodgerblue4')) + scale_size_manual(values = c(3,2,2)) + theme(text = element_text(size = 16)) + scale_y_continuous('Predicted prob. of being reviewed\n', labels = percent) + scale_x_continuous("") + ggtitle("Central trend lines.\n")
plot(p)